apiVersion: v1
kind: Pod
metadata:
  name: du-node-1
  annotations:
    k8s.v1.cni.cncf.io/networks: netattach1 
spec:
  containers:
  - name: du
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
  nodeSelector:
    site: cell
