kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# One control plane node and three "workers".
#
# While these will not add more real compute capacity and
# have limited isolation, this can be useful for testing
# rolling updates etc.
#
# The API-server and other control plane components will be
# on the control-plane node.
#
# You probably don't need this unless you are testing Kubernetes itself.
# You need Flannel CNI binary in each Node CNI binary path '/opt/cni/bin'
nodes:
- role: control-plane
  image: qarham/kindest-node:v1.19
  extraMounts:
  - hostPath: /root/q-k8s/mac-kind/plugins/bin
    containerPath: /opt/cni/bin
- role: worker
  image: qarham/kindest-node:v1.19
  extraMounts:
  - hostPath: /root/q-k8s/mac-kind/plugins/bin
    containerPath: /opt/cni/bin
- role: worker
  image: qarham/kindest-node:v1.19
  extraMounts:
  - hostPath: /root/q-k8s/mac-kind/plugins/bin
    containerPath: /opt/cni/bin
networking:
  disableDefaultCNI: true # disable kindnet
