apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crpds.junos.config
spec:
  scope: Namespaced
  group: junos.config
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: CrpdConfig
    plural: crpds
    singular: crpd
    shortNames:
      - cc
  additionalPrinterColumns:
    - name: Type
      type: string
      priority: 0
      JSONPath: .spec.name
      description: The type of the database that should be created
    - name: Duration
      type: string
      priority: 0
      JSONPath: .spec.duration
      description: For how long.

